# Generated by Django 4.1.7 on 2023-03-22 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschrijving', models.TextField(blank=True)),
                ('compleet', models.BooleanField(default=False)),
                ('datumAangemaakt', models.DateTimeField(auto_now_add=True)),
                ('datumKlaar', models.DateTimeField(blank=True, null=True)),
                ('gebruiker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['compleet'],
            },
        ),
    ]
